<?php

require_once __DIR__ . '/../../../libraries/Elasticsearch/Model/Aggregation.php';

use PHPUnit\Framework\TestCase;

class Model_AggregationTest extends TestCase
{
    /**
     * @var Elasticsearch_Model_Aggregation
     */
    public $aggregation;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->aggregation = new Elasticsearch_Model_Aggregation('foo', 'Foo', 'bar', 12);
    }

    public function testBuildsAggregation(): void
    {
        $expected = [
            'terms' => [
                'field' => 'bar',
                'size' => 12
            ]
        ];
        $this->assertEquals($expected, $this->aggregation->toArray());
    }

    public function testReturnsName(): void {
        $this->assertEquals('foo', $this->aggregation->getName());
    }

    public function testReturnsLabel(): void {
        $this->assertEquals('Foo', $this->aggregation->getLabel());
    }
}
